config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "links#index"
  resources :links do
    member do
    put "like", to: "links#upvote"
    put "dislike", to: "links#downvote"
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :links
         # a user belongs to another user? what is this helper method doing for you?
         belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  # looks ..... scaffolded, which is ok so long as you know what it does.
  # Avoid generators if you can, creates alot of extra files you won't use.
  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      # as we learned in class, the respond_to allows us to respond to JSON, not always neccessary, but is if you want a JSON endpoint for your database.
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 def upvote
   @link = Link.find(params[:id])
   @link.upvote_by current_user
   redirect_to :back
 end
 def downvote
   @link = Link.find(params[:id])
   @link.downvote_from current_user
   redirect_to :back
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JINEX</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%=stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans:700' %>
</head>
<body class="img-back">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <header class="navbar" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <div id="override-logo" class="navbar-brand">JIN<span>EX<span><%= link_to "", root_path %></div>
          <nav class="collapse navbar-collapse navbar-ex1-collapse">
          	<% if user_signed_in? %>
  						<ul id="custom" class="nav navbar-nav navbar-right">
                <li><%= link_to 'Home', '/' %></li>
  							<li><%= link_to 'New Link', new_link_path %></li>
  							<li><%= link_to 'Account', edit_user_registration_path %></li>
  							<li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  						</ul>
  					<% else %>
  						<ul class="nav navbar-nav pull-right">
  							<li><%= link_to 'Sign up', new_user_registration_path %></li>
  							<li><%= link_to 'Sign in', new_user_session_path %></li>
  						</ul>
  					<% end %>
          </nav>
        </div>
      </div>
    </header>
<div id="container" class="col-md-9 center-block">
<%= yield %>
</div>
</body>
</html>

app/views/links/_form.html.erb
<div class="move-right">
  <%= form_for(@link) do |f| %>
    <% if @link.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

        <ul>
        <% @link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <div class="navbar-form">
    <div class="field form-custom">
      <%= f.label :title %><br>
      <%= f.text_field :title, placeholder: '"ESPN"' %>
    </div>
    <div class="field form-custom">
      <%= f.label :url %><br>
      <%= f.text_field :url, placeholder: '"www.espn.com"' %>
    </div>
    <div class="field form-custom-area">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    </div>
    <div class="submit-btn form-custom">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/links/edit.html.erb
<h1 class="move-right">Editing Link</h1>

<%= render 'form' %>

app/views/links/index.html.erb
<% @links.each do |link| %>
  <div class="link row clearfix move-right">
    <h2>
      <%= link_to link.title, link %><br>
      <div class="author">Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.email %></div>
    </h2>

    <div class="btn-group">
      <a class="btn btn-default btn-sm" href="<%= link.url %>">Visit URL</a>
      <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        <%= link.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        <%= link.get_downvotes.size %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/links/new.html.erb
<h1 class="move-right">Create a New Link!</h1>

<%= render 'form' %>
<div class="navbar-form">
</div>

app/views/links/show.html.erb
<div class="page-header">
  <h2><a href="<%= @link.url %>"><%= @link.title %></a><br> <small>Submitted by <%= @link.user.email %></small></h2>
</div>

<div>
  <%= @link.description %>
</div>

<div class="btn-group">
	<%= link_to 'Visit URL', @link.url, class: "btn btn-primary" %>
</div>
<div class="btn-group move-right">
  <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-up"></span>
    <%= @link.get_upvotes.size %>
  <% end %>
  <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-down">
    <%= @link.get_downvotes.size %>
  <% end %>
</div>

<% if @link.user == current_user -%>
	<div class="btn-group">
		<%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default" %>
		<%= link_to 'Delete', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
	</div>
<% end %>